name: Generate TTNN MD Files

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Build pipeline run ID to download artifacts from'
        required: true
        type: string
  push:
    branches:
      - ddilbaz/pages-workflow
    paths:
      - 'docs/src/ops/ttnn/**'

jobs:
  generate_md:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tenstorrent/tt-torch/tt-torch-ci-ubuntu-22-04:latest
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "work-dir=$(pwd)" >> "$GITHUB_OUTPUT"
          echo "install-output-dir=$(pwd)/install" >> "$GITHUB_OUTPUT"
          echo "test-output-dir=$(pwd)/results/models/tests/" >> "$GITHUB_OUTPUT"

      - name: Git safe dir
        run: git config --global --add safe.directory ${{ steps.strings.outputs.work-dir }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: models_op_per_op.xlsx
          path: ${{ steps.strings.outputs.work-dir }}/results

      - name: Configure Git User
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create necessary directories
        shell: bash
        run: |
          mkdir -p ${{ steps.strings.outputs.work-dir }}/docs/src/ops/ttnn

      - name: Generate TTNN MD Files and Commit if Changes Exist
        shell: bash
        run: |
          source env/activate
          python ${{ steps.strings.outputs.work-dir }}/tt_torch/tools/generate_md.py --excel_path ${{ steps.strings.outputs.work-dir }}/results/models_op_per_op.xlsx --md_dir docs/src/ops/ttnn --json_dir docs/src/ops/ttnn
          # List newly generated files
          NEW_FILES=(docs/src/ops/ttnn/ttnn*.md docs/src/ops/ttnn/ttnn*.json)

          # Remove files not in the new generation
          git rm $(git ls-files 'docs/src/ops/ttnn/ttnn*.md' 'docs/src/ops/ttnn/ttnn*.json' | \
            grep -vFf <(printf '%s\n' "${NEW_FILES[@]}"))

          # Stage new and modified files
          git add "${NEW_FILES[@]}"

          # Commit only if changes exist
          if ! git diff --staged --quiet; then
            git commit -m "Update TTNN files from latest generation"
            git push origin ${GITHUB_REF#refs/heads/}
          fi

      - name: Upload TTNN MD Files to archive
        uses: actions/upload-artifact@v4
        with:
          name: ttnn-md
          path: ${{ steps.strings.outputs.work-dir }}/docs/src/ops/ttnn
