name: Generate TTNN MD Files

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Build pipeline run ID to download artifacts from'
        required: true
        type: string
  push:
    branches:
      - ddilbaz/pages-workflow
    paths:
      - 'docs/ops/ttnn/**'

jobs:
  generate_md:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tenstorrent/tt-torch/tt-torch-ci-ubuntu-22-04:latest
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "work-dir=$(pwd)" >> "$GITHUB_OUTPUT"
          echo "install-output-dir=$(pwd)/install" >> "$GITHUB_OUTPUT"
          echo "test-output-dir=$(pwd)/results/models/tests/" >> "$GITHUB_OUTPUT"

      - name: Git safe dir
        run: git config --global --add safe.directory ${{ steps.strings.outputs.work-dir }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: models_op_per_op.xlsx
          path: ${{ steps.strings.outputs.work-dir }}/results

      - name: Clean existing MD/JSON files
        shell: bash
        run: |
          # Remove existing files from git tracking
          git rm -f docs/ops/ttnn/*.md docs/ops/ttnn/*.json || true
          # Commit the removal
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git commit -m "Remove old TTNN MD/JSON files before regeneration" || true

      - name: Create necessary directories
        shell: bash
        run: |
          mkdir -p ${{ steps.strings.outputs.work-dir }}/docs/ops/ttnn

      - name: Generate TTNN MD Files
        shell: bash
        run: |
          source env/activate
          python ${{ steps.strings.outputs.work-dir }}/tt_torch/tools/generate_md.py --excel_path ${{ steps.strings.outputs.work-dir }}/results/models_op_per_op.xlsx --md_dir ${{ steps.strings.outputs.work-dir }}/docs/ops/ttnn --json_dir ${{ steps.strings.outputs.work-dir }}/docs/ops/ttnn

      - name: Add and commit new files
        shell: bash
        run: |
          # Add newly generated files
          git add docs/ops/ttnn/*.md docs/ops/ttnn/*.json
          # Commit new files
          git commit -m "Update TTNN MD/JSON files from latest generation"
          # Push changes
          git push origin ${GITHUB_REF#refs/heads/}

      - name: Upload TTNN MD Files to archive
        uses: actions/upload-artifact@v4
        with:
          name: ttnn-md
          path: ${{ steps.strings.outputs.work-dir }}/docs/ops/ttnn
