# This workflow automates running model tests.

name: Nightly Tests

on:
  schedule:
    - cron: '0 4 * * *'  # Runs at 04:00 UTC every day
  workflow_dispatch:  # Manual trigger


jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
    secrets: inherit
  spdx:
    uses: ./.github/workflows/spdx.yml
    secrets: inherit
  docker-build:
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
  build:
    needs: [pre-commit, spdx, docker-build]
    uses: ./.github/workflows/run-build.yml
    secrets: inherit
    with:
      docker-image: ${{ needs.docker-build.outputs.docker-image }}
  run-benchmark:
    needs: [docker-build, build]
<<<<<<< HEAD
    uses: ./.github/workflows/run-op-by-op-model-tests-nightly.yml
=======
    uses: ./.github/workflows/run-depth-benchmark-tests.yml
>>>>>>> e5146fc (Add dummy test suite to test out changes from main dev branch)
    secrets: inherit
    with:
      docker-image: ${{ needs.docker-build.outputs.docker-image }}
