name: Run Model Tests

on:
  workflow_dispatch:
  workflow_call:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  tests:
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        build: [
          {runs-on: n150, n300, name: "ttrt_run1", runner_idx: 0, runner_total: 3},
          {runs-on: n150, n300, name: "ttrt_run2", runner_idx: 1, runner_total: 3},
          {runs-on: n300, n150, name: "ttrt_run3", runner_idx: 2, runner_total: 3},
        ]
    runs-on:
      - ${{ matrix.build.runs-on }}

    container:
      image: ghcr.io/tenstorrent/tt-torch/tt-torch-ci-ubuntu-22-04:latest
      options: --user root --device /dev/tenstorrent/0
      volumes:
        - /dev/hugepages:/dev/hugepages
        - /dev/hugepages-1G:/dev/hugepages-1G
        - /etc/udev/rules.d:/etc/udev/rules.d
        - /lib/modules:/lib/modules
        - /opt/tt_metal_infra/provisioning/provisioning_env:/opt/tt_metal_infra/provisioning/provisioning_env

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true

    - name: Set reusable strings
      id: strings
      shell: bash
      env:
        job-name: "${{ github.job }} (${{ matrix.build.runs-on }}, ${{ matrix.build.name }}"
      run: |
        echo "work-dir=$(pwd)" >> "$GITHUB_OUTPUT"
        echo "build-output-dir=$(pwd)/build" >> "$GITHUB_OUTPUT"
        echo "install-output-dir=$(pwd)/install" >> "$GITHUB_OUTPUT"
        echo "test-output-dir=$(pwd)/results/models/tests/" >> "$GITHUB_OUTPUT"
        # Github job context unfortunately doesn't contain job_id, this is the workaround how to fetch it using GH API
        echo "Expected job name: ${{ env.job-name }}"
        JOB_ID=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}/jobs" | \
          jq -r '.jobs[] | select(.name | contains("${{ env.job-name }}")) | .id ')
        echo "Current job id: $JOB_ID"
        echo "job-id=$JOB_ID" >> "$GITHUB_OUTPUT"

    - name: Git safe dir
      run: git config --global --add safe.directory ${{ steps.strings.outputs.work-dir }}

    - name: Use build artifacts
      uses: actions/download-artifact@v4
      with:
        name: install-artifacts
        path: ${{ steps.strings.outputs.install-output-dir }}

    - name: 'Untar install directory'
      shell: bash
      working-directory: ${{ steps.strings.outputs.install-output-dir }}
      run: tar xvf artifact.tar

    - name: make directories
      shell: bash
      working-directory: ${{ steps.strings.outputs.install-output-dir }}
      run: |
        mkdir -p ${{ steps.strings.outputs.work-dir }}/third_party/tt-mlir/src/tt-mlir/third_party/tt-metal/src/tt-metal
        mkdir -p ${{ steps.strings.outputs.work-dir }}/env

    - name: copy tt-metal and env dirs
      shell: bash
      working-directory: ${{ steps.strings.outputs.install-output-dir }}
      run: |
        cp -r ${{ steps.strings.outputs.install-output-dir }}/tt-metal/* ${{ steps.strings.outputs.work-dir }}/third_party/tt-mlir/src/tt-mlir/third_party/tt-metal/src/tt-metal
        cp -r ${{ steps.strings.outputs.install-output-dir }}/env/env/* ${{ steps.strings.outputs.work-dir }}/env

    - name: Run Model Tests
      shell: bash
      run: |
        echo ${{ steps.strings.outputs.work-dir }}
        echo ${{ steps.strings.outputs.test-output-dir }}
        echo ${{ steps.strings.outputs.build-output-dir }}
        echo ${{ steps.strings.outputs.install-output-dir }}
        source env/activate
        export LD_LIBRARY_PATH="/opt/ttmlir-toolchain/lib/:${{ steps.strings.outputs.install-output-dir }}/lib:${{ steps.strings.outputs.build-output-dir }}/lib:./lib/:${LD_LIBRARY_PATH}"
        mkdir -p ${{ steps.strings.outputs.work-dir }}/third_party/tt-mlir/src/tt-mlir-build/bin/
        cp ${{ steps.strings.outputs.install-output-dir }}/lib/ttmlir-opt ${{ steps.strings.outputs.work-dir }}/third_party/tt-mlir/src/tt-mlir-build/bin/
        chmod +x ${{ steps.strings.outputs.work-dir }}/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt
        cp ${{ steps.strings.outputs.install-output-dir }}/lib/ttmlir-translate ${{ steps.strings.outputs.work-dir }}/third_party/tt-mlir/src/tt-mlir-build/bin/
        chmod +x ${{ steps.strings.outputs.work-dir }}/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-translate
        cp ${{ steps.strings.outputs.work-dir }}/results/models_op_per_op.xlsx results/
        #export TT_TORCH_COMPILE_DEPTH=COMPILE_OP_BY_OP
        #for testname in ${{ matrix.build.test_names }}; do
        #testname=${testname//,/}
        #echo "running test: $testname"
        #pytest -v tests/models/$testname
        #done
        python results/run_ttir_test.py --runner_total=${{ matrix.build.runner_total }} --runner_idx=${{ matrix.build.runner_idx }}

    - name: Tar results
      shell: bash
      working-directory: ${{ steps.strings.outputs.test-output-dir }}
      run: |
        tar cvf ${{ matrix.build.name }}_${{ steps.strings.outputs.job-id }}.tar .

    - name: Upload test folder to archive
      uses: actions/upload-artifact@v4
      with:
        name: test-reports-${{ matrix.build.name }}.tar
        path: ${{ steps.strings.outputs.test-output-dir }}/${{ matrix.build.name }}_${{ steps.strings.outputs.job-id }}.tar
