name: spdx

on:
  workflow_dispatch:
  workflow_call:

jobs:
  check-spdx-headers:

    timeout-minutes: 10
    runs-on: n300
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - uses: enarx/spdx@master
      with:
        licenses: |-
          Apache-2.0
          MIT
